//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index_nb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_nb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Views.Home.Index.nb", typeof(Index_nb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraktalkaos.
        /// </summary>
        public static string FractalChaos {
            get {
                return ResourceManager.GetString("FractalChaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaos spillet er et matematisk spill med veldig enkle regler som lager bemerkelsesverdige fraktalstrukturer. .
        /// </summary>
        public static string FractalChaosTextLong {
            get {
                return ResourceManager.GetString("FractalChaosTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hjem.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo! Jeg er Morten. Jeg er en programmerer med en interesse i datavisualisering. Jeg elsker å bygge raske og responsive webapplikasjoner..
        /// </summary>
        public static string IntroPart1 {
            get {
                return ResourceManager.GetString("IntroPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg studerte teoretisk fysikk og jeg er særlig interessert i kaotiske systemer..
        /// </summary>
        public static string IntroPart2 {
            get {
                return ResourceManager.GetString("IntroPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Språk:.
        /// </summary>
        public static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bbbb.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
