//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal Chaos.
        /// </summary>
        public static string FractalChaos {
            get {
                return ResourceManager.GetString("FractalChaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chaos game is a game of very simple rules that produces remarkable fractal structures. This post explores a variety of different structures and the code used to generate them..
        /// </summary>
        public static string FractalChaosTextLong {
            get {
                return ResourceManager.GetString("FractalChaosTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! I&apos;m Morten. I&apos;m a software developer with a passion for data visualisation. I have a keen interest in the latest developments in web frameworks and building powerful web applications. .
        /// </summary>
        public static string IntroPart1 {
            get {
                return ResourceManager.GetString("IntroPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have a background in Theoretical Physics and I have a particular interest in Quantum Computing..
        /// </summary>
        public static string IntroPart2 {
            get {
                return ResourceManager.GetString("IntroPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menger Sponge.
        /// </summary>
        public static string Menger {
            get {
                return ResourceManager.GetString("Menger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Menger sponge is a three-dimensional fractal curve that exhibits infinite surface area and zero volume. This shows the POV-Ray code to render this mathematical structure.
        /// </summary>
        public static string MengerTextLong {
            get {
                return ResourceManager.GetString("MengerTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Menger sponge is a three-dimensional fractal curve with infinite surface area.
        /// </summary>
        public static string MengerTextShort {
            get {
                return ResourceManager.GetString("MengerTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaaa.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-Scroll Unified Chaotic System.
        /// </summary>
        public static string TSUCS {
            get {
                return ResourceManager.GetString("TSUCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Three-Scroll Unified Chaotic System is a chaotic system that contains both a Lorenz-style attractor and also a Lu Chen-style attractor at its extremes..
        /// </summary>
        public static string TSUCSTextLong {
            get {
                return ResourceManager.GetString("TSUCSTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Three-Scroll Unified Chaotic System is a chaotic system that contains both a Lorenz-style attractor and also a Lu Chen-style attractor at its extremes..
        /// </summary>
        public static string TSUCSTextShort {
            get {
                return ResourceManager.GetString("TSUCSTextShort", resourceCulture);
            }
        }
    }
}
