//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular D3.
        /// </summary>
        public static string AngularD3 {
            get {
                return ResourceManager.GetString("AngularD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D3.js is a versatile and powerful library for manipulating data in documents. AngularJS is a framework for developing single page applications. This post combines D3.js with AngularJS in order to manipulate settings for a force-directed graph in real-time..
        /// </summary>
        public static string AngularD3TextLong {
            get {
                return ResourceManager.GetString("AngularD3TextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining D3.js with AngularJS.
        /// </summary>
        public static string AngularD3TextShort {
            get {
                return ResourceManager.GetString("AngularD3TextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermodynamics, Computation and Irreversibility.
        /// </summary>
        public static string Computations {
            get {
                return ResourceManager.GetString("Computations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermodynamics, Computation and Irreversibility.
        /// </summary>
        public static string ComputationsTextLong {
            get {
                return ResourceManager.GetString("ComputationsTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal Chaos.
        /// </summary>
        public static string FractalChaos {
            get {
                return ResourceManager.GetString("FractalChaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chaos game is a game of very simple rules that produces remarkable fractal structures. This post explores a variety of different structures and the code used to generate them..
        /// </summary>
        public static string FractalChaosTextLong {
            get {
                return ResourceManager.GetString("FractalChaosTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! I&apos;m Morten. I&apos;m a software developer with an interest in visualisations of chaotic mathematical systems.  .
        /// </summary>
        public static string IntroPart1 {
            get {
                return ResourceManager.GetString("IntroPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a collection of a few of the things I find interesting.
        /// </summary>
        public static string IntroPart2 {
            get {
                return ResourceManager.GetString("IntroPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorenz Attractor.
        /// </summary>
        public static string Lorenz {
            get {
                return ResourceManager.GetString("Lorenz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lorenz attractor is a chaotic system that arises out of three simple differential equations. This shows the POV-Ray code necessary to simulate this system. .
        /// </summary>
        public static string LorenzTextLong {
            get {
                return ResourceManager.GetString("LorenzTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lorenz attractor is a chaotic system that arises out of three simple differential equations..
        /// </summary>
        public static string LorenzTextShort {
            get {
                return ResourceManager.GetString("LorenzTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menger Sponge.
        /// </summary>
        public static string Menger {
            get {
                return ResourceManager.GetString("Menger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Menger sponge is a three-dimensional fractal curve that exhibits infinite surface area and zero volume. This shows the POV-Ray code to render this mathematical structure.
        /// </summary>
        public static string MengerTextLong {
            get {
                return ResourceManager.GetString("MengerTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Menger sponge is a three-dimensional fractal curve with infinite surface area.
        /// </summary>
        public static string MengerTextShort {
            get {
                return ResourceManager.GetString("MengerTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peter De Jong .
        /// </summary>
        public static string PeterDeJong {
            get {
                return ResourceManager.GetString("PeterDeJong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaotic attractors are mathematical systems that evolve over time. The Peter De Jong attractor is an especially elegant system, calculated by very simple trigonometry..
        /// </summary>
        public static string PeterDeJongTextLong {
            get {
                return ResourceManager.GetString("PeterDeJongTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Peter De Jong attractor is an especially elegant system, calculated by very simple trigonometry..
        /// </summary>
        public static string PeterDeJongTextShort {
            get {
                return ResourceManager.GetString("PeterDeJongTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaaa.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-Scroll Unified Chaotic System.
        /// </summary>
        public static string TSUCS {
            get {
                return ResourceManager.GetString("TSUCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Three-Scroll Unified Chaotic System is a chaotic system that contains both a Lorenz-style attractor and also a Lu Chen-style attractor at its extremes..
        /// </summary>
        public static string TSUCSTextLong {
            get {
                return ResourceManager.GetString("TSUCSTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Three-Scroll Unified Chaotic System is a chaotic system that contains both a Lorenz-style attractor and also a Lu Chen-style attractor at its extremes..
        /// </summary>
        public static string TSUCSTextShort {
            get {
                return ResourceManager.GetString("TSUCSTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words within Words.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief look at words contained within other words and interesting word chains.
        /// </summary>
        public static string WordsTextLong {
            get {
                return ResourceManager.GetString("WordsTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief look at words contained within other words.
        /// </summary>
        public static string WordsTextShort {
            get {
                return ResourceManager.GetString("WordsTextShort", resourceCulture);
            }
        }
    }
}
